### ISSUE TITLE
Cannot install on linux

### ISSUE THREAD

**Issue by ppanero** [lief-project/packages#1]
```
sudo pip install LIEF-0.7.0-Linux.tar.gz
```
Get as output
```
Processing ./LIEF-0.7.0-Linux.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
    IOError: [Errno 2] No such file or directory: '/tmp/pip-EAZbfz-build/setup.py'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-EAZbfz-build/
````

pip is upgraded and up to date (version 9.0.1)

Checking a bit the package, it does not have a setup.py file.

**Comment by romainthomas** [comment]
Well, ``LIEF-0.7.0-Linux.tar.gz`` is the **SDK** not the python package...

Use ``https://github.com/lief-project/LIEF/releases/download/0.7.0/linux_lief-0.7.0_py2.7.tar.gz``

**Comment by ppanero** [comment]
I tried the pythong package before:
```
pip install linux_lief-0.7.0_py2.7.tar.g
Collecting linux_lief-0.7.0_py2.7.tar.g
  Could not find a version that satisfies the requirement linux_lief-0.7.0_py2.7.tar.g (from versions: )
No matching distribution found for linux_lief-0.7.0_py2.7.tar.g
```

But it doesnt seem to support CentOS :( Am I wrong?

**Comment by romainthomas** [comment]
I think you forgot the **z** (py2.7.tar.g**z**). Indeed there are some troubles for CentOS but you can use the This dockerfile: https://github.com/lief-project/Dockerlief/blob/master/dockerlief/dockerfiles/centos.docker

**Comment by ppanero** [comment]
Yes you where right sorry for that.
